panel/authentication/urls.py
from django.urls import path

from .views.authentication import LoginPageView, LogoutView

app_name = 'authentication'

urlpatterns = [
	path('login/', LoginPageView.as_view(), name='login'),
	path('logout/', LogoutView.as_view(), name='logout'),
]

panel/dashboard/urls.py
from django.urls import path

from .views import DashboardPageView

app_name = 'dashboard'

urlpatterns = [
    path('', DashboardPageView.as_view(), name='dashboard'),
]

project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    path('', include('panel.dashboard.urls')),
    path('auth/', include("panel.authentication.urls")),
]

panel/authentication/views/authentication.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.models import User
from django.contrib import messages
from django.views.generic.base import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin


class LoginPageView(TemplateView):

    template_name = "login.html"

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('dashboard:dashboard')
        return self.render_to_response({})

    def post(self, request, *args, **kwargs):
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_staff:
                user.save()
                login(request, user)
                return redirect('dashboard:dashboard')
            else:
                messages.error(request, "You're not and admin. Please login as one.")
                return self.render_to_response({})
        else:
            messages.error(request, "Incorrect Username or Password")
            return self.render_to_response({})

class LogoutView(LoginRequiredMixin, TemplateView):

    def get(self, request, *args, **kwargs):
        logout(request)
        return redirect('authentication:login')

panel/dashboard/views.py
from django.views.generic.base import TemplateView
from django.http import JsonResponse
from django.contrib import messages
from django.shortcuts import render, redirect

class DashboardPageView(TemplateView):

    template_name = "dashboard.html"

    def get(self, request, *args, **kwargs):

        if request.user.is_authenticated:

            return self.render_to_response({
                'status' : "OKE" 
            })
        return redirect('authentication:login')

panel/authentication/templates/login.html
{% load static %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no" name="viewport">
  <title>Login</title>

  <!-- General CSS Files -->
  <link rel="stylesheet" href="https://connect.nos.wjv-1.neo.id/assets/css/bootstrap.min.css">
  <link rel="stylesheet" href="{% static 'fontawesome/css/all.min.css' %}">

  <!-- Template CSS -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/components.css' %}">
</head>

<body>
  <div id="app">
    <section class="section">
      <div class="container mt-5">
        <div class="row">
          <div class="col-12 col-sm-8 offset-sm-2 col-md-6 offset-md-3 col-lg-6 offset-lg-3 col-xl-4 offset-xl-4">

            <div class="card card-primary">
              <div class="card-header"><h4>Login</h4></div>

              <div class="card-body">
                <form class="user" action="{% url 'authentication:login' %}" method="POST">
                  {% csrf_token %}
                  {% if messages %}
                      {% for message in messages %}
                      <div class="alert message-{{ message.tags }} alert-dismissible" role="alert">
                          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                              <span aria-hidden="true">&times;</span>
                          </button>
                          <div class="message-{{ message.tags }}">{{ message }}</div>
                      </div>
                      {% endfor %}
                  {% endif %} 
                  <div class="form-group">
                    <label for="email">Username</label>
                    <input type="text" class="form-control" id="username" name="username" placeholder="Enter username" tabindex="1" required autofocus>
                    <div class="invalid-feedback">
                      Please fill in your username
                    </div>
                  </div>

                  <div class="form-group">
                    <div class="d-block">
                      <label for="password" class="control-label">Password</label>
                      <div class="float-right">
                        <a href="auth-forgot-password.html" class="text-small">
                          Forgot Password?
                        </a>
                      </div>
                    </div>
                    <input type="password" class="form-control" id="password" name="password" tabindex="2" placeholder="Enter password" required="">
                    <div class="invalid-feedback">
                      please fill in your password
                    </div>
                  </div>

                  <div class="form-group">
                    <div class="custom-control custom-checkbox">
                      <input type="checkbox" name="remember" class="custom-control-input" tabindex="3" id="remember-me">
                      <label class="custom-control-label" for="remember-me">Remember Me</label>
                    </div>
                  </div>

                  <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-lg btn-block" tabindex="4">
                      Login
                    </button>
                  </div>
                </form>
              </div>
            </div>
            <div class="simple-footer">
              Copyright &copy; Dailysocial 2019
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>

  <!-- General JS Scripts -->
  <script src="https://connect.nos.wjv-1.neo.id/assets/js/core/jquery.min.js"></script>
  <script src="https://connect.nos.wjv-1.neo.id/assets/js/core/popper.min.js"></script>
  <script src="https://connect.nos.wjv-1.neo.id/assets/js/core/bootstrap.min.js"></script>
  
</body>
</html>

panel/dashboard/templates/dashboard.html
{% extends "base.html" %}

{% block doctitle %}
Dashboard | Dashboard
{% endblock doctitle %}

{% block content %}
	{% if user.is_authenticated %}
		<div class="row">
          <h1>OKE</h1>
    </div>
	{% endif %}
{% endblock content %}

panel/templates/base.html
<html lang="en">

<head>
  <meta charset="utf-8" />
  <link rel="apple-touch-icon" sizes="76x76" href="../assets/img/apple-icon.png">
  <link rel="icon" type="image/png" href="../assets/img/favicon.png">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <title>
    {% block doctitle %}
    {% endblock doctitle %}
  </title>
  <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
  <!--     Fonts and icons     -->
  <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
  <!-- CSS Files -->
  <link href="https://connect.nos.wjv-1.neo.id/assets/css/bootstrap.min.css" rel="stylesheet" />
  <link href="https://connect.nos.wjv-1.neo.id/assets/css/paper-dashboard.css?v=2.0.0" rel="stylesheet" />
  <!-- CSS Just for demo purpose, don't include it in your project -->
  <link href="https://connect.nos.wjv-1.neo.id/assets/demo/demo.css" rel="stylesheet" />

  <link rel="stylesheet" href="/static/css/tagsinput.css" />

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/themes/base/jquery-ui.css" type="text/css" media="all" />

  {% block extrastyle %}
  {% endblock extrastyle %}
</head>

<body class="">
  <div class="wrapper ">
    <div class="sidebar" data-color="white" data-active-color="danger">
      {% include "sidebar.html" %}
    </div>
    <div class="main-panel">
      <!-- Navbar -->
      {% include "topbar.html" %}
      <div class="content">
        
        {% if messages %}
          {% for message in messages %}
              <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
            {% endfor %}
        {% endif %}
        {% block content %}{% endblock content %}
      </div>
      <footer class="footer footer-black  footer-white ">
        <div class="container-fluid">
          <div class="row">
            <nav class="footer-nav">
              <ul>
                <li>&nbsp;
                </li>
              </ul>
            </nav>
            <div class="credits ml-auto">
              <span class="copyright">
                ©
                <script>
                  document.write(new Date().getFullYear())
                </script>, made with <i class="fa fa-heart heart"></i> by Dailysocial ID
              </span>
            </div>
          </div>
        </div>
      </footer>
    </div>
  </div>
  <!--   Core JS Files   -->
  <script src="https://connect.nos.wjv-1.neo.id/assets/js/core/jquery.min.js"></script>
  <script src="https://connect.nos.wjv-1.neo.id/assets/js/core/popper.min.js"></script>
  <script src="https://connect.nos.wjv-1.neo.id/assets/js/core/bootstrap.min.js"></script>
  <script src="https://connect.nos.wjv-1.neo.id/assets/js/plugins/perfect-scrollbar.jquery.min.js"></script>
  <!--  Notifications Plugin    -->
  <script src="https://connect.nos.wjv-1.neo.id/assets/js/plugins/bootstrap-notify.js"></script>
  <!-- Chart JS -->
  <script src="https://connect.nos.wjv-1.neo.id/assets/js/plugins/chartjs.min.js"></script>
  <!-- Control Center for Now Ui Dashboard: parallax effects, scripts for the example pages etc -->
  <script src="https://connect.nos.wjv-1.neo.id/assets/js/paper-dashboard.min.js?v=2.0.0" type="text/javascript"></script>
  <!-- Paper Dashboard DEMO methods, don't include it in your project! -->
  <script src="https://connect.nos.wjv-1.neo.id/assets/demo/demo.js"></script>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js" type="text/javascript"></script>

  <script src="/static/js/tagsinput.js"></script>

  {% block extrascript %}
  {% endblock extrascript %}
 
</body>

</html>

panel/templates/sidebar.html
{% load static %}
<div class="logo">
  <a href="http://www.creative-tim.com" class="simple-text logo-mini">
    <div class="logo-image-small">
      <img src="{% static 'image/logo-small.png' %}">
    </div>
  </a>
  <a href="http://www.creative-tim.com" class="simple-text logo-normal">
    Dashboard
    <!-- <div class="logo-image-big">
      <img src="../assets/img/logo-big.png">
    </div> -->
  </a>
</div>

panel/templates/topbar.html
      <nav class="navbar navbar-expand-lg navbar-absolute fixed-top navbar-transparent">
        <div class="container-fluid">
          <div class="navbar-wrapper">
            <div class="navbar-toggle">
              <button type="button" class="navbar-toggler">
                <span class="navbar-toggler-bar bar1"></span>
                <span class="navbar-toggler-bar bar2"></span>
                <span class="navbar-toggler-bar bar3"></span>
              </button>
            </div>
            {% block content_title %}
              <a class="navbar-brand" href="#pablo">Athena Dashboard</a>
            {% endblock content_title %}
          </div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-bar navbar-kebab"></span>
            <span class="navbar-toggler-bar navbar-kebab"></span>
            <span class="navbar-toggler-bar navbar-kebab"></span>
          </button>
          <div class="collapse navbar-collapse justify-content-end" id="navigation">
            <ul class="navbar-nav">
              <li class="nav-item btn-rotate dropdown">
                <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="fa fa-user-circle"></i>
                  <p>
                    <span class="d-lg-none d-md-block">Some Actions</span>
                  </p>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="#">Profile</a>
                  <a class="dropdown-item" href="{% url 'authentication:logout' %}">Logout</a>
                </div>
              </li>
            </ul>
          </div>
        </div>
      </nav>